# Site settings
title: Natalia Folcini
description: Rising Data Scientist
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "https://nfolcini.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Natalia Folcini
user_description: 7 Years of Very Successful Experience in Data Analysis, Industry Analysis, Technology Strategy, Market Research, Financial Analysis, Business Valuations, and Consulting at top tech and consulting companies including The Gartner Group/Dataquest, Intel, and Cap Gemini. My passion is driving product innovation and improving processes by conducting data-driven research & analysis using cutting-edge machine learning techniques complemented by user research, strategic industry analysis, financial analysis, and business intelligence

github_username:  nfolcini


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
