# Site settings
title: Natalia Folcini, BereMBA, MSEE, CFA
description: Rising Data Scientist
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "https://nfolcini.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Natalia Folcini
user_description: 7 Years of Very Successful Experience in Data Analysis, Industry Analysis, Technology Strategy, Market Research, Financial Analysis, Business Valuations, and Consulting at companies including The Gartner Group/Dataquest, Intel, Cap Gemini, Frost & Sullivan, and Telefonica de Argentina -- focusing on Disruptive Technologies
user_title: Software Developer
email: folcini@mba.berkeley.edu

github_username:  nfolcini


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
